{"uuid": "b2a9210c-daaf-46dd-90bd-0941a3aa3421", "children": ["3e5aa412-fb56-4d8d-a348-b314c1277679"], "befores": [{"name": "browser", "status": "broken", "statusDetails": {"message": "ValueError: no option named 'playwright-browser'\n", "trace": "  File \"/home/user/.local/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/user/.local/lib/python3.10/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"/home/user/.local/lib/python3.10/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/user/.local/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/home/user/.local/lib/python3.10/site-packages/_pytest/fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/home/user/Documents/QA_Automation_projects/Pytest/Playwright - Pytest-Automationexercise/conftest.py\", line 18, in browser\n    browser_name = pytestconfig.getoption(\"playwright-browser\")\n  File \"/home/user/.local/lib/python3.10/site-packages/_pytest/config/__init__.py\", line 1704, in getoption\n    raise ValueError(f\"no option named {name!r}\") from e\n"}, "start": 1746788476708, "stop": 1746788476709}], "start": 1746788476708, "stop": 1746788476759}