{"uuid": "bc2c16a0-eaf1-4c89-a7ea-f0ae51733af0", "children": ["02c683c0-c724-4f89-827f-4a83dd5e964c"], "befores": [{"name": "browser", "status": "broken", "statusDetails": {"message": "ValueError: no option named 'playwright-browser'\n", "trace": "  File \"/home/user/.local/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/user/.local/lib/python3.10/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"/home/user/.local/lib/python3.10/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/user/.local/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/home/user/.local/lib/python3.10/site-packages/_pytest/fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/home/user/Documents/QA_Automation_projects/Pytest/Playwright - Pytest-Automationexercise/conftest.py\", line 18, in browser\n    browser_name = pytestconfig.getoption(\"playwright-browser\")\n  File \"/home/user/.local/lib/python3.10/site-packages/_pytest/config/__init__.py\", line 1704, in getoption\n    raise ValueError(f\"no option named {name!r}\") from e\n"}, "start": 1746788476377, "stop": 1746788476377}], "start": 1746788476377, "stop": 1746788476426}