{"name": "User Login Test with Correct Credentials", "status": "broken", "statusDetails": {"message": "playwright._impl._errors.Error: BrowserType.launch: Executable doesn't exist at /home/user/.cache/ms-playwright/webkit-2083/pw_run.sh\n╔════════════════════════════════════════════════════════════╗\n║ Looks like Playwright was just installed or updated.       ║\n║ Please run the following command to download new browsers: ║\n║                                                            ║\n║     playwright install                                     ║\n║                                                            ║\n║ <3 Playwright Team                                         ║\n╚════════════════════════════════════════════════════════════╝", "trace": "pytestconfig = <_pytest.config.Config object at 0x7f350cbf32e0>\n\n    @pytest.fixture(scope=\"function\")\n    def browser(pytestconfig):\n        \"\"\"Запускаємо обраний браузер на основі CLI аргументу\"\"\"\n        browser_name = pytestconfig.getoption(\"playwright_browser\")\n    \n        with sync_playwright() as p:\n>           browser = p[browser_name].launch(headless=HEADLESS)\n\nconftest.py:21: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/home/user/.local/lib/python3.10/site-packages/playwright/sync_api/_generated.py:14440: in launch\n    self._sync(\n/home/user/.local/lib/python3.10/site-packages/playwright/_impl/_browser_type.py:95: in launch\n    Browser, from_channel(await self._channel.send(\"launch\", params))\n/home/user/.local/lib/python3.10/site-packages/playwright/_impl/_connection.py:59: in send\n    return await self._connection.wrap_api_call(\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <playwright._impl._connection.Connection object at 0x7f3507cb3820>\ncb = <function Channel.send.<locals>.<lambda> at 0x7f3507c27520>\nis_internal = False\n\n    async def wrap_api_call(\n        self, cb: Callable[[], Any], is_internal: bool = False\n    ) -> Any:\n        if self._api_zone.get():\n            return await cb()\n        task = asyncio.current_task(self._loop)\n        st: List[inspect.FrameInfo] = getattr(task, \"__pw_stack__\", inspect.stack())\n        parsed_st = _extract_stack_trace_information_from_stack(st, is_internal)\n        self._api_zone.set(parsed_st)\n        try:\n            return await cb()\n        except Exception as error:\n>           raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\nE           playwright._impl._errors.Error: BrowserType.launch: Executable doesn't exist at /home/user/.cache/ms-playwright/webkit-2083/pw_run.sh\nE           ╔════════════════════════════════════════════════════════════╗\nE           ║ Looks like Playwright was just installed or updated.       ║\nE           ║ Please run the following command to download new browsers: ║\nE           ║                                                            ║\nE           ║     playwright install                                     ║\nE           ║                                                            ║\nE           ║ <3 Playwright Team                                         ║\nE           ╚════════════════════════════════════════════════════════════╝\n\n/home/user/.local/lib/python3.10/site-packages/playwright/_impl/_connection.py:520: Error"}, "description": "Test for logging in with correct credentials and verifying account functionalities", "start": 1746789547514, "stop": 1746789547514, "uuid": "73a854f9-888e-4eca-8221-fdf04db1b21e", "historyId": "457fcc14aedfd12601d9ecddada12aca", "testCaseId": "457fcc14aedfd12601d9ecddada12aca", "fullName": "test.test_2_login_user_delete#test_login_user_with_correct_credentials", "labels": [{"name": "parentSuite", "value": "test"}, {"name": "suite", "value": "test_2_login_user_delete"}, {"name": "host", "value": "user-VivoBook-15-ASUS-Laptop-X540UBR"}, {"name": "thread", "value": "109595-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_2_login_user_delete"}]}