{"uuid": "ceead036-71be-4c47-ac19-a2c31ebdd4f6", "children": ["3b39a5f8-d9a7-4c43-8eb1-5fb5e7098506"], "befores": [{"name": "browser", "status": "broken", "statusDetails": {"message": "ValueError: no option named 'playwright-browser'\n", "trace": "  File \"/home/user/.local/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/user/.local/lib/python3.10/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"/home/user/.local/lib/python3.10/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/user/.local/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/home/user/.local/lib/python3.10/site-packages/_pytest/fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/home/user/Documents/QA_Automation_projects/Pytest/Playwright - Pytest-Automationexercise/conftest.py\", line 18, in browser\n    browser_name = pytestconfig.getoption(\"playwright-browser\")\n  File \"/home/user/.local/lib/python3.10/site-packages/_pytest/config/__init__.py\", line 1704, in getoption\n    raise ValueError(f\"no option named {name!r}\") from e\n"}, "start": 1746788476561, "stop": 1746788476561}], "start": 1746788476561, "stop": 1746788476620}